### ISSUE TITLE
Task: move middleware contracts into a separate repo

### ISSUE THREAD

**Issue by samlaf** [Layr-Labs/eigenlayer-contracts#139]
## Description

Would be best to have the middleware contracts in a separate repo. They are currently in the [avs-unstable](https://github.com/Layr-Labs/eigenlayer-contracts/tree/avs-unstable/src/contracts/middleware) branch. I had to ask Jeff today to merge master into avs-unstable since it had fallen behind by 300+ commits and had a few merge conflicts.

The dependencies with eigensdk and incredible-squaring currently look like:
![IMG_5C022598C8DE-1 2](https://github.com/Layr-Labs/eigenlayer-contracts/assets/9342524/e669962e-fe88-4677-a7cd-a7f9fc017f8e)

the deploy script for eigenlayer-core contracts is in master (eigensdk uses the contract addresses stored in the output config file in that branch), and incredible-squaring deploys the middleware contracts (registry contracts are stored in the avs-unstable and avs-unstable-require-opt-into-slashing branches). It would be best if incredible-squaring was pointing to another repo with the contracts, instead of a branch, the middleware contracts' dependency on the core contracts would be more obvious (that new repo would branch to a specific commit of eigenlayer-contracts).

### Action Items
- [ ] Move middleware contracts into another repo (maybe named eigenlayer-avs-contracts?)
- [ ] Move blspubkey compendium to core contracts directory (it should now be shared by all avs teams)
- [ ] Make sure to also move tests and deployment scripts

**Comment by ChaoticWalrus** [comment]
Agreed this is something we should do.
Currently development is spread across several branches which would make this fairly hellish to accomplish; we anticipate being able to get this done after closing out the major development branches.
This should align well with plans to improve our "git hygiene" with better branch management, and splitting the repos may also help with differentiating the docs for AVS developers vs. the docs for developers who want to integrate with EigenLayer "core".
