### ISSUE TITLE
Create a Strategy Deployment script for avs teams to use

### ISSUE THREAD

**Issue by samlaf** [Layr-Labs/eigenlayer-contracts#140]
My current understanding (correct me if I'm wrong) is that AVS teams that have their own token (aka most of them) will need to deploy a strategy for their token. I've looked through our deploy scripts and haven't found one for this specific purpose. The closest I've found is [this one](https://github.com/Layr-Labs/eigenlayer-contracts/blob/master/script/misc/DeployGoerliStrategy.s.sol) which deploys a strategy for some hardcoded token.

Should we have such a script, or am I thinking about this wrong?

**Comment by ChaoticWalrus** [comment]
> My current understanding (correct me if I'm wrong) is that AVS teams that have their own token (aka most of them) will need to deploy a strategy for their token. I've looked through our deploy scripts and haven't found one for this specific purpose. The closest I've found is [this one](https://github.com/Layr-Labs/eigenlayer-contracts/blob/master/script/misc/DeployGoerliStrategy.s.sol) which deploys a strategy for some hardcoded token.
> 
> Should we have such a script, or am I thinking about this wrong?

I think because Strategies still need to be whitelisted, it makes sense for EigenLabs to do this deployment. That being said, it would still probably be good to have a simple script for this.
