### ISSUE TITLE
Documentation: M1=>M2 Transition for EigenPods contracts (EigenPodManager, EigenPods, BeaconChainProofs)

### ISSUE THREAD

**Issue by ChaoticWalrus** [Layr-Labs/eigenlayer-contracts#155]
## Description
Should contain a brief list of changes for the M1 to M2 transition. This includes: 

- Paused to unpaused
- Contract upgrades
- Functions/vars added/removed/changed

### Action Items
- [x] PR with draft documentation
- [x] Get review
- [x] Merge PR

### Blocking Issues
N/A

**Comment by Sidu28** [comment]
Closed with this PR: https://github.com/Layr-Labs/eigenlayer-contracts/pull/211
