### ISSUE TITLE
Feature: One step to stake & restake

### ISSUE THREAD

**Issue by LouisWT** [Layr-Labs/eigenlayer-contracts#21]
**User story**
Now, Users have to stake on Lido or Rpl before restaking, which is pretty annoying if they have ETH now.
So, maybe we can provide a function called **depositEthIntoStrategy** to make user stake ETH on Lido/Rpl and restake on Eigen in a single step.

**Actions**
If user called depositEthIntoStrategy,
- staking Lido/Rpl(user's option) by calling Lido/Rpl contract 
- restaking by our strategy.

**Acceptance criteria**
- Support stake & restake ETH in a single step.

**Comment by haythemsellami** [comment]
I guess this could be done in a wrapper contract, right?

**Comment by 0xClandestine** [comment]
#### Challenge Accepted 🫡
I took on the challenge to learn more about EigenLayer and created a "zap" contract for 1-step ETH deposits in both Lido and RocketPool. This contract uses the `depositEthIntoStrategyWithSignature` method, allowing users to approve other accounts for depositing on their behalf. 

Check out the "zap" contract implementation here on GitHub: https://github.com/0xClandestine/eigenzap/tree/main
___
NOTE: Just a heads up, I put this together today, and while it works, the testing coverage is still quite low.
