### ISSUE TITLE
EigenPod: Edge case in `mostRecentBalanceUpdateTimestamp` when proving multiple withdrawals out of order

### ISSUE THREAD

**Issue by wadealexc** [Layr-Labs/eigenlayer-contracts#240]
From discussion here: https://github.com/Layr-Labs/eigenlayer-contracts/pull/238#discussion_r1357421778

The gist is that `mostRecentBalanceUpdateTimestamp` can be updated inconsistently depending on the order in which you prove withdrawals.

**Comment by Sidu28** [comment]
Ok, I don't think I agree with the suggestion made to set mostRecentBalanceUpdateTimestamp  to oracleTimestamp.  Apart from not being as intuitive, proving withdrawals is permissionless, and setting it as such would brick proving any older withdrawals.  I think the correct solution here is to  set it to withdrawal timestamp, and if the withdrawals are out of order, just check if withdrawal timestamp > validatorInfo.mostRecentBalanceUpdateTimestamp, and only update it then

**Comment by ChaoticWalrus** [comment]
> Ok, I don't think I agree with the suggestion made to set mostRecentBalanceUpdateTimestamp to oracleTimestamp. Apart from not being as intuitive, proving withdrawals is permissionless, and setting it as such would brick proving any older withdrawals. I think the correct solution here is to set it to withdrawal timestamp, and if the withdrawals are out of order, just check if withdrawal timestamp > validatorInfo.mostRecentBalanceUpdateTimestamp, and only update it then

Doesn't this mean that the current logic would brick withdrawals when proving them out of order? Am I missing something here? Would it just make more sense to set the timestamp to zero or something in these cases?

**Comment by wadealexc** [comment]
Closing this because the consensus is that no update to the balance update timestamp is needed when processing full withdrawals.
