### ISSUE TITLE
Scoping: Decide whether or not we are removing “stake update pushes” (coupling between EigenLayer and EigenDA) for M2 mainnet

### ISSUE THREAD

**Issue by ChaoticWalrus** [Layr-Labs/eigenlayer-contracts#276]
## Description
At present, the DelegationManager pushes stake updates to EigenDA, and EigenDA only.
This was initially introduced as a "BandAid" type of solution, to ensure that stake updates to EigenDA would be timely on testnet. However, we will still need to find a solution for other AVSs, for both testnet and mainnet.
It's likely that this solution will be satisfactory for EigenDA as well, but at the moment that is still TBD.
The intention is to eventually remove this coupling regardless, but we need to reach a definitive decision on if this coupling will be removed prior to the M2 mainnet release.

### Action Items
- [ ] Prepare doc explaining decision to be made
- [ ] Meeting to reach / ratify decision
- [ ] Share decision with any impacted parties
- [ ] Tickets for any next steps (if applicable)

### Blocking Issues
As explained in the description, this decision is rather blocked by finding another solution for stake updates. Actually removing these updates will be quick if we decide to get rid of them, so it's fine to procrastinate on this decision for a while until more context is available.

**Comment by wadealexc** [comment]
We removed it; closing this issue.
