### ISSUE TITLE
Design: Post-M2 Slashing Architecture

### ISSUE THREAD

**Issue by ChaoticWalrus** [Layr-Labs/eigenlayer-contracts#278]
## Description
A large feature to (eventually) be added to EigenLayer post-M2 release is support for slashing.
We have had a number of previous discussions, and there was a preliminary slashing design that was removed from the contracts (in a couple PRs -- notably https://github.com/Layr-Labs/eigenlayer-contracts/pull/234 and https://github.com/Layr-Labs/eigenlayer-contracts/pull/181) after slashing was ruled out-of-scope for M2.
This tickets prompts its assignee to help synthesize the previous discussions and work into understandable + digestible docs, and continue to move the discussion forward on implementing this feature.
**The primary goals here are deciding on the scope and "high-level" design/spec for slashing, for the release following the M2 release.**

### Action Items
- [ ] Summarize past work + discussions in a doc, and share it
- [ ] Prepare docs + hold discussions as necessary to agree on scoping and design/spec
- [ ] Share the final decisions
- [ ] Create tickets for implementation and link them back to the doc capturing final key decisions

### Blocking Issues
N/A

**Comment by gpsanant** [comment]
Starting design here: https://docs.google.com/document/d/1-IyvOluiYUw-Lg01r38OGD-L5P_wGVwCW_VeiJJNGR8/edit?usp=sharing

**Comment by ChaoticWalrus** [comment]
closing as outdated
