### ISSUE TITLE
Test: StrategyManager Unit Test Refactor

### ISSUE THREAD

**Issue by ypatil12** [Layr-Labs/eigenlayer-contracts#284]
## Description
Refactor StrategyManager unit tests for simplicity and clarity

### Action Items
- [x] Update StrategyManager Unit Tests per standard defined in [Test Practices Doc](https://docs.google.com/document/d/107Wn4cVjSOTng1T72TWhhzswj1Afw4Dz7fUXQWqzLT0/edit)
- [ ] Update testing doc with potential invariants to monitor and integration test TODOs

**Comment by ChaoticWalrus** [comment]
The relevant PR was merged (https://github.com/Layr-Labs/eigenlayer-contracts/pull/293)
Closing this issue out now.
