### ISSUE TITLE
Test: DelegationManager Unit Test Refactor

### ISSUE THREAD

**Issue by ypatil12** [Layr-Labs/eigenlayer-contracts#285]
## Description
Refactor DelegationManager unit tests for simplicity and clarity

### Action Items
- [ ] Update DelegationManager Unit Tests per standard defined in [Test Practices Doc](https://docs.google.com/document/d/107Wn4cVjSOTng1T72TWhhzswj1Afw4Dz7fUXQWqzLT0/edit)
- [ ] Update testing doc with potential invariants to monitor and integration test TODOs

**Comment by ChaoticWalrus** [comment]
The relevant PR got merged https://github.com/Layr-Labs/eigenlayer-contracts/pull/332 so I'm going to close this issue out.
