### ISSUE TITLE
Add comment explaining why we are pushing to eigenDA's stakeRegistry in DelegationManager

### ISSUE THREAD

**Issue by samlaf** [Layr-Labs/eigenlayer-contracts#291]
We've made the temporary choice to push DM updates to eigenDA's stakeRegistry for the upcoming M2 testnet launch.
The code was updated with functions such as https://github.com/Layr-Labs/eigenlayer-contracts/blob/5429ebe43084d386e43fa6620b36bfbec540ce93/src/contracts/core/DelegationManager.sol#L664 without adding proper explaining comments. @NimaVaziri was even confused this morning as to why we need to write eigenSync (the binary run by AVS teams to call updateStakes() periodically) if the DM is already pushing its stake updates.

This issue, along with https://github.com/Layr-Labs/eigenlayer-middleware/issues/27, is a request to please please add detailed comments in the code where temporary decisions are made. As I've mentioned before, our contracts are starting to be external facing, and we need to maintain a level of respect for external dev's time, who don't have access to all of our internal docs detailing temporary decisions. These should be explicited in the code, where applies.

**Comment by wadealexc** [comment]
we aren't doing this anymore (for mainnet), so closing this issue.
