### ISSUE TITLE
Bug: middleware folder referenced in AVS Guide does not exist 

### ISSUE THREAD

**Issue by bowenli86** [Layr-Labs/eigenlayer-contracts#314]
**Describe the bug**

https://github.com/Layr-Labs/eigenlayer-contracts/blob/master/docs/experimental/AVS-Guide.md refers to "middleware folder" in a few places, but the folder doesn't exist

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
Enter important environment info needed to reproduce the bug. 
 - [e.g. chrome, safari]
 - [e.g. version]

**Don't Forget To**
* Assign this to a project (our default is [eigenlayer](https://github.com/orgs/Layr-Labs/projects/3/))
* Add priority + size estimate
* Set status to New

**Comment by bowenli86** [comment]
@samlaf @cryptogakusei  if you can take a look?

**Comment by samlaf** [comment]
Thanks! AVS-guide should be removed from this repo. All middlware contracts have been moved to eigenlayer-middleware repo. We need to fix the links in https://github.com/Layr-Labs/eigenlayer-middleware/blob/master/docs/AVS-Guide.md.
