### ISSUE TITLE
Feature: 1-step deposits for RP and Lido (EigenZap) 

### ISSUE THREAD

**Issue by 0xClandestine** [Layr-Labs/eigenlayer-contracts#374]
#### Description
I took on the challenge to learn more about EigenLayer and drafted a "zap" contract for 1-step ETH deposits in both Lido and RocketPool. This contract uses the `depositEthIntoStrategyWithSignature` method, allowing users to approve other accounts for depositing on their behalf.

#### Benefits
* **Cost Efficiency**: Users enjoy reduced gas costs for deposits, contributing to overall affordability.

* **Seamless User Experience**: Users can provide ETH directly through the EigenLayer frontend, eliminating the need to navigate away, unless they specifically desire cbETH exposure. This ensures a smooth and uninterrupted user journey.

#### Implementation
Check out the "zap" contract implementation here on GitHub: https://github.com/0xClandestine/eigenzap/tree/main

#### Notes
Just a heads up, I put this together today, and while it works, the testing coverage is still quite low.  Also, I've created this issue to enhance its visibility, especially considering that issue #21 has been lingering for quite some time.

**Comment by ChaoticWalrus** [comment]
Neat. All looks correct from a glance.
