### ISSUE TITLE
Task: Update Docs to reflect Holesky deployment

### ISSUE THREAD

**Issue by joan-el** [Layr-Labs/eigenlayer-contracts#492]
## Description
The section under "M1 (Current Goerli Testnet Deployment)" of https://github.com/Layr-Labs/eigenlayer-contracts/tree/master#introduction is not longer applicable, the new Holesky deployment info can be provided there.

### Action Items
- [ ] Doc update

### Blocking Issues
n/a

**Comment by Chizobaonorh** [comment]
I will love to contribute to this
