### ISSUE TITLE
Pragma statements in mainnet branch and testnet-holesky don't match

### ISSUE THREAD

**Issue by MauroToscano** [Layr-Labs/eigenlayer-contracts#520]
Pragma statements in mainnet branch and testnet-holesky don't match

It can be checked that contract files are different with 

```git diff --name-only testnet-holesky mainnet```

Running a git diff will of a file will show up the difference is in the pragma statement. Ex:

```git diff testnet-holesky mainnet src/contracts/core/AVSDirectory.sol```

```
-pragma solidity ^0.8.12;
+pragma solidity =0.8.12;
```

**Comment by ChaoticWalrus** [comment]
yes, this was changed.
