### ISSUE TITLE
How to calculate points of a specific wallet address

### ISSUE THREAD

**Issue by adnansudozai** [Layr-Labs/eigenlayer-contracts#531]
I am currently working on integrating Eagenlayer into my wallet application and have successfully implemented staking, unstaking, and withdrawal functionalities. However, I am facing an issue regarding the display of staking points for users and the total points of each token. I would like to know if there is an available API or any other method to obtain the points for any token.

I would really appreciate any guidance or assistance in this matter, as I am looking for a way to effectively communicate the users' staking points for every token within my app. Your help would be highly valuable in enhancing the user experience and ensuring the success of my project.

Thank you in advance for your time and expertise.

**Comment by DaWe35** [comment]
Hi, same here, can you please provide a CSV including addresses and amounts for each participants, like other airdrops did? I'd like to add the Eigen airdrop to [AirdropScan](https://airdropscan.org/)
Thank you 🙏
