### ISSUE TITLE
Feature: Share airdrop eligibility list as csv

### ISSUE THREAD

**Issue by DaWe35** [Layr-Labs/eigenlayer-contracts#552]
**User story**
Sharing airdrop eligibility lists (addresses and amounts) public benefits all Eigen users since other projects (like [Rotki](https://github.com/rotki/rotki) or [AirdropScan](https://airdropscan.org/)) can list Eigen and notify Eigen users about their eligibility.

It's basically free marketing for Eigen and great content for other projects. All the big airdrops share their list publicly, eg Uniswap, Omni, Optimism, Arbitrum, [etc.](https://github.com/rotki/data/tree/develop/airdrops)

**Actions**
- [ ] Compile CSV with addresses, amounts
- [ ] Upload & share

**Comment by Chizobaonorh** [comment]
I will love to work on this, please assign this to me and add me as a contributor
