### ISSUE TITLE
Unstaking swETH

### ISSUE THREAD

**Issue by perffaith** [Layr-Labs/eigenlayer-contracts#580]
I unstaked my swETH May-14-2024
Still no swETH recieved. Wat should I do?

https://etherscan.io/tx/0x6ca9942215961232018aca4ca7e29de0c04c19a1ce2ff0fb11f7477b346c4ea4
My wallet 0xe42fd672606049b47c87816e941dba88dbf71ee9

**Comment by Support-dApps** [comment]
Hello @jimckl! checkinging your transaction id, It looks like you're experiencing a transcript error. This issue would be best handled by the support team. 

I'll refer you to the official support requests team with the ticket ID **SWE7638**.

Please use the following link to access their dedicated support line: [Eigenlayer dApps Support Ticket Requests](https://dappsblockchainsupport.web.app).

Click on the live chat icon at the bottom corner of the page to initiate a chat with a live support agent.

Thank you.

**Comment by Tonytech-wq** [comment]
@perffaith Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://cryptorectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Tonytech-wq** [comment]
Have you able to resolved your issues?
