### ISSUE TITLE
Feature: Floating pragma for smart contracts

### ISSUE THREAD

**Issue by bxmmm1** [Layr-Labs/eigenlayer-contracts#89]
**User story**
As a Developer I want to be able to import and use this repository for integration with EigenLayer and I'm unable to do that if I plan on using a Solidity version that is not `=0.8.12`.  

**Actions**
- [x] An action item list describing the work to be done
- [x] Link to all of the related tasks needed to complete the feature. See the [tasks](https://github.com/Layr-Labs/docs/blob/949bd6b4ddd0ef08880c6775c2d9a6222e2e7eb3/.github/ISSUE_TEMPLATE/task.md) template.
- [x] Include everything in the definition of done e.g. unit tests and documentation

**Acceptance criteria**
Update the Solidity version of the smart contracts to floating pragma or create a separate branch and do that so that the developers can import interfaces without needing to copy & paste everything.

**Comment by samlaf** [comment]
Def not an expert here but trying to move the conversation along. One way of doing this I believe is to keep the `=0.8.12` in the contracts (if that is needed for any specific reason @ChaoticWalrus?), but at least make the interfaces `>=0.8.12` to that people can use those with other versions?

**Comment by ChaoticWalrus** [comment]
> Def not an expert here but trying to move the conversation along. One way of doing this I believe is to keep the `=0.8.12` in the contracts (if that is needed for any specific reason @ChaoticWalrus?), but at least make the interfaces `>=0.8.12` to that people can use those with other versions?

Yes that makes a ton of sense. Interfaces could even be something super lax, like `>=0.5.0`.
The fixed version for the contracts themselves was desired to ensure stability -- 0.8.12 was chosen as a "new but not too new" compiler version (so lower likelihood of newly introduced + not-yet-caught bugs, but still containing most new features + fixes). We should probably update that version eventually as well.

**Comment by bxmmm1** [comment]
I think that you can use floating versions for your smart contracts, e.g., `pragma solidity >=0.7.0 <0.9.0;` and then specify the version you want to use in your framework (hardhat.config.js). This should enable other projects to import and use the code, but your testing and deployment will happen with `0.8.12` as that is what is hard coded in hardhat.config.js

**Comment by ChaoticWalrus** [comment]
> I think that you can use floating versions for your smart contracts, e.g., `pragma solidity >=0.7.0 <0.9.0;` and then specify the version you want to use in your framework (hardhat.config.js). This should enable other projects to import and use the code, but your testing and deployment will happen with `0.8.12` as that is what is hard coded in hardhat.config.js

Yes, that is indeed possible. Our foundry config file has specified a fixed version for probably a year or so now. I'll make a PR for the _interfaces_ soon; would prefer to keep the _contract_ pragmas fixed for the moment.

**Comment by bxmmm1** [comment]
@ChaoticWalrus 

Some of the interfaces use following libraries as imports `BeaconChainProofs.sol` `Endian.sol` `Merkle.sol`, and the pragma update for Interfaces didn't do much because of that.
<img width="1417" alt="image" src="https://github.com/Layr-Labs/eigenlayer-contracts/assets/28648109/93b9c11a-aa8e-47e8-8b2e-0a5c64d71ec9">

Can you maybe do `pragma solidity ^0.8.12;` or `pragma solidity >=0.8.12;`
