### ISSUE TITLE
Duplicate remappings

### ISSUE THREAD

**Issue by adlerjohn** [Layr-Labs/eigenlayer-contracts#9]
Remapping are duplicated here

https://github.com/Layr-Labs/eigenlayer-contracts/blob/b1efe8b1ca6295ba124d6a46bb2cae531bdae3c7/foundry.toml#L6-L11

and here

https://github.com/Layr-Labs/eigenlayer-contracts/blob/b1efe8b1ca6295ba124d6a46bb2cae531bdae3c7/remappings.txt#L1-L4

Only one (either) is necessary.

**Comment by haythemsellami** [comment]
https://github.com/Layr-Labs/eigenlayer-contracts/pull/37
